//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHasaby.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyHasaby.lang.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supplier.
        /// </summary>
        internal static string addsup {
            get {
                return ResourceManager.GetString("addsup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration of product branches.
        /// </summary>
        internal static string bra1 {
            get {
                return ResourceManager.GetString("bra1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item quantity.
        /// </summary>
        internal static string bra2 {
            get {
                return ResourceManager.GetString("bra2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold out.
        /// </summary>
        internal static string bra3 {
            get {
                return ResourceManager.GetString("bra3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing price.
        /// </summary>
        internal static string bra4 {
            get {
                return ResourceManager.GetString("bra4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selling price.
        /// </summary>
        internal static string bra5 {
            get {
                return ResourceManager.GetString("bra5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned.
        /// </summary>
        internal static string bra6 {
            get {
                return ResourceManager.GetString("bra6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        internal static string bra7 {
            get {
                return ResourceManager.GetString("bra7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string bra8 {
            get {
                return ResourceManager.GetString("bra8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registration.
        /// </summary>
        internal static string btntasgil {
            get {
                return ResourceManager.GetString("btntasgil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string cos {
            get {
                return ResourceManager.GetString("cos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string ECuntry {
            get {
                return ResourceManager.GetString("ECuntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record customer data.
        /// </summary>
        internal static string emi1 {
            get {
                return ResourceManager.GetString("emi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        internal static string emi2 {
            get {
                return ResourceManager.GetString("emi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string EName {
            get {
                return ResourceManager.GetString("EName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code here.
        /// </summary>
        internal static string EntAcount {
            get {
                return ResourceManager.GetString("EntAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.
        /// </summary>
        internal static string EPhone {
            get {
                return ResourceManager.GetString("EPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show subcategories.
        /// </summary>
        internal static string fre1 {
            get {
                return ResourceManager.GetString("fre1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string fre2 {
            get {
                return ResourceManager.GetString("fre2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string fre3 {
            get {
                return ResourceManager.GetString("fre3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold out.
        /// </summary>
        internal static string fre4 {
            get {
                return ResourceManager.GetString("fre4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residual.
        /// </summary>
        internal static string fre5 {
            get {
                return ResourceManager.GetString("fre5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buying.
        /// </summary>
        internal static string fre6 {
            get {
                return ResourceManager.GetString("fre6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sale.
        /// </summary>
        internal static string fre7 {
            get {
                return ResourceManager.GetString("fre7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to earning.
        /// </summary>
        internal static string fre8 {
            get {
                return ResourceManager.GetString("fre8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application manager.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer report.
        /// </summary>
        internal static string home1 {
            get {
                return ResourceManager.GetString("home1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction report.
        /// </summary>
        internal static string home2 {
            get {
                return ResourceManager.GetString("home2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category management.
        /// </summary>
        internal static string home3 {
            get {
                return ResourceManager.GetString("home3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier management.
        /// </summary>
        internal static string home4 {
            get {
                return ResourceManager.GetString("home4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string home5 {
            get {
                return ResourceManager.GetString("home5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a backup databases.
        /// </summary>
        internal static string home6 {
            get {
                return ResourceManager.GetString("home6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore the databases.
        /// </summary>
        internal static string home7 {
            get {
                return ResourceManager.GetString("home7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing databases.
        /// </summary>
        internal static string home8 {
            get {
                return ResourceManager.GetString("home8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier debt.
        /// </summary>
        internal static string moerd {
            get {
                return ResourceManager.GetString("moerd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string moerd1 {
            get {
                return ResourceManager.GetString("moerd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Supplier.
        /// </summary>
        internal static string moerd2 {
            get {
                return ResourceManager.GetString("moerd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account registration.
        /// </summary>
        internal static string nam1 {
            get {
                return ResourceManager.GetString("nam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name.
        /// </summary>
        internal static string nam2 {
            get {
                return ResourceManager.GetString("nam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a phone number.
        /// </summary>
        internal static string nam3 {
            get {
                return ResourceManager.GetString("nam3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category.
        /// </summary>
        internal static string pro {
            get {
                return ResourceManager.GetString("pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a category.
        /// </summary>
        internal static string pro1 {
            get {
                return ResourceManager.GetString("pro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string pro2 {
            get {
                return ResourceManager.GetString("pro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show branches.
        /// </summary>
        internal static string pro3 {
            get {
                return ResourceManager.GetString("pro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a branch.
        /// </summary>
        internal static string pro4 {
            get {
                return ResourceManager.GetString("pro4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new category.
        /// </summary>
        internal static string san {
            get {
                return ResourceManager.GetString("san", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register customer data.
        /// </summary>
        internal static string san2 {
            get {
                return ResourceManager.GetString("san2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount.
        /// </summary>
        internal static string san3 {
            get {
                return ResourceManager.GetString("san3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your notes.
        /// </summary>
        internal static string san4 {
            get {
                return ResourceManager.GetString("san4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share databases over the Internet.
        /// </summary>
        internal static string shar {
            get {
                return ResourceManager.GetString("shar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share databases.
        /// </summary>
        internal static string shar1 {
            get {
                return ResourceManager.GetString("shar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the category.
        /// </summary>
        internal static string tae {
            get {
                return ResourceManager.GetString("tae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new supplier.
        /// </summary>
        internal static string title1 {
            get {
                return ResourceManager.GetString("title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditor.
        /// </summary>
        internal static string tons7 {
            get {
                return ResourceManager.GetString("tons7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debtor.
        /// </summary>
        internal static string tons8 {
            get {
                return ResourceManager.GetString("tons8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To communicate.
        /// </summary>
        internal static string tos {
            get {
                return ResourceManager.GetString("tos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        internal static string tos2 {
            get {
                return ResourceManager.GetString("tos2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string tos3 {
            get {
                return ResourceManager.GetString("tos3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone call.
        /// </summary>
        internal static string tos4 {
            get {
                return ResourceManager.GetString("tos4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatsApp.
        /// </summary>
        internal static string tos5 {
            get {
                return ResourceManager.GetString("tos5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the activation code.
        /// </summary>
        internal static string tos6 {
            get {
                return ResourceManager.GetString("tos6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction report.
        /// </summary>
        internal static string trans {
            get {
                return ResourceManager.GetString("trans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total debt.
        /// </summary>
        internal static string translab1 {
            get {
                return ResourceManager.GetString("translab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        internal static string translab2 {
            get {
                return ResourceManager.GetString("translab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total paid.
        /// </summary>
        internal static string translab3 {
            get {
                return ResourceManager.GetString("translab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Suppliers.
        /// </summary>
        internal static string viewsup {
            get {
                return ResourceManager.GetString("viewsup", resourceCulture);
            }
        }
    }
}
